# Generated by Django 3.2 on 2021-04-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя лектора')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия лектора')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия студента')),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('students', models.ManyToManyField(to='academy.Student')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.lecturer')),
            ],
        ),
    ]
